name = "github-hackathon-app1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Development environment
[env.development]
vars = { NODE_ENV = "development" }

# Production environment
[env.production]
vars = { NODE_ENV = "production" }

# Secrets are managed via Cloudflare Dashboard or wrangler commands
# wrangler pages secret put DAILY_API_KEY --project-name github-hackathon-app1
