name = "github-hackathon-app1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Production environment only
[env.production]
vars = { 
  NODE_ENV = "development",
  VITE_FIREBASE_API_KEY = "your_firebase_api_key_here",
  VITE_FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com",
  VITE_FIREBASE_DATABASE_URL = "https://your_project-default-rtdb.firebaseio.com",
  VITE_FIREBASE_PROJECT_ID = "your_project_id",
  VITE_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com",
  VITE_FIREBASE_MESSAGING_SENDER_ID = "your_messaging_sender_id",
  VITE_FIREBASE_APP_ID = "your_app_id",
  VITE_FIREBASE_MEASUREMENT_ID = "your_measurement_id"
}
