name = "github-hackathon-app1"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Preview environment (for testing)
[env.preview]
vars = { NODE_ENV = "preview" }

# Production environment
[env.production]
vars = { NODE_ENV = "production" }

# Secrets are managed via Cloudflare Dashboard or wrangler commands
# For production: wrangler pages secret put DAILY_API_KEY --project-name github-hackathon-app1
# For local development: use .dev.vars file
